title: "Moyan Liu"
description: "PhD Student | Climate Systems & Control Researcher"
email: "your.email@domain.com"
url: "https://moyan-liu.github.io"

author:
  name: "Moyan Liu"
  avatar: "/assets/images/profile.jpg"  # Add your profile pic here
  bio: "Researcher in chaos theory, Lorenz models, and weather system control"

social:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/moyan-liu"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://linkedin.com/in/YOURNAME"
  - label: "Google Scholar"
    icon: "ai ai-google-scholar"
    url: "https://scholar.google.com/citations?user=YOUR_ID"
